//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m3uParser.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sample {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sample() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("m3uParser.Tests.Sample", typeof(Sample).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EXTM3U url-tvg=&quot;http://www.teleguide.info/download/new3/jtv.zip&quot; m3uautoload=1 cache=500 deinterlace=1 tvg-shift=0
        ///#EXTINF:-1 tvgname=&quot;Первый_канал&quot; tvglogo=&quot;Первый канал&quot; grouptitle=&quot;Каналы ЦЭТВ РТРС&quot; ,Первый канал
        ///http://192.168.1.1:4022/udp/225.77.225.1:5000
        ///#EXTINF:-1 tvg-name=&quot;Россия_1&quot; tvg-logo=&quot;Россия&quot; ,Россия
        ///http://192.168.1.1:4022/udp/225.77.225.2:5000
        ///#EXTINF:-1 tvg-name=&quot;Матч!&quot; tvg-logo=&quot;Матч ТВ&quot; ,Матч ТВ
        ///http://192.168.1.1:4022/udp/225.77.225.3:5000.
        /// </summary>
        internal static string header_with_parameters {
            get {
                return ResourceManager.GetString("header_with_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EXTM3U
        ///#EXT-X-PLAYLIST-TYPE:VOD
        ///#EXT-X-TARGETDURATION:10
        ///#EXT-X-VERSION:3
        ///#EXT-X-MEDIA-SEQUENCE:0
        ///#EXTINF:10.0,
        ///http://example.com/movie1/fileSequenceA.ts
        ///#EXTINF:10.0,
        ///http://example.com/movie1/fileSequenceB.ts
        ///#EXTINF:10.0,
        ///http://example.com/movie1/fileSequenceC.ts
        ///#EXTINF:9.0,
        ///http://example.com/movie1/fileSequenceD.ts
        ///#EXT-X-ENDLIST.
        /// </summary>
        internal static string simple_vod {
            get {
                return ResourceManager.GetString("simple_vod", resourceCulture);
            }
        }
    }
}
